# Copyright © 2020 Interplanetary Database Association e.V.,
# Planetmint and IPDB software contributors.
# SPDX-License-Identifier: (AGPL-3.0-or-later AND CC-BY-4.0)
# Code is AGPL-3.0-or-later and docs are CC-BY-4.0

version: '2.2'

#! still requires a valid Planetmint image to be published 
# until then the environment can be initialized locally by using https://github.com/planetmint/planetmint/blob/main/docker-compose.yml
services:
  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: mongod
    restart: always

  tarantool:
    image: tarantool/tarantool:2.10.4
    ports:
      - "5200:5200"
      - "3301:3301"
      - "3303:3303"
      - "8081:8081"
    volumes:
      - ./compose/tarantool/init.lua:/opt/tarantool/init.lua
    command: tarantool /opt/tarantool/init.lua
    restart: always

  planetmint:
    depends_on:
      - mongodb
      - tendermint
      - tarantool
    image: planetmint/planetmint:latest
    environment:
      PLANETMINT_DATABASE_BACKEND: tarantool_db
      PLANETMINT_DATABASE_HOST: tarantool
      PLANETMINT_DATABASE_PORT: 3303
      PLANETMINT_SERVER_BIND: 0.0.0.0:9984
      PLANETMINT_WSSERVER_HOST: 0.0.0.0
      PLANETMINT_WSSERVER_ADVERTISED_HOST: planetmint
      PLANETMINT_TENDERMINT_HOST: tendermint
      PLANETMINT_TENDERMINT_PORT: 26657
    ports:
      - "9984:9984"
      - "9985:9985"
      - "26658"
      - "2222:2222"
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "curl http://planetmint:9984 && curl http://tendermint:26657/abci_query"
        ]
      interval: 3s
      timeout: 5s
      retries: 5
    command: 'scripts/entrypoint.sh'
    restart: always

  tendermint:
    image: tendermint/tendermint:v0.34.15
    # volumes:
    #   - ./tmdata:/tendermint
    entrypoint: ''
    ports:
      - "26656:26656"
      - "26657:26657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --rpc.laddr=tcp://0.0.0.0:26657 --proxy_app=tcp://planetmint:26658"
    restart: always
